services:
  postgres:
    image: postgres:16
    container_name: airwatch_postgres
    environment:
      POSTGRES_DB: airwatch
      POSTGRES_USER: airwatch
      POSTGRES_PASSWORD: airwatch_pw
    ports:
      - "5433:5432"
    volumes:
      - airwatch_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: airwatch_redis
    ports:
      - "6379:6379"

  api:
    build: ../apps/api
    container_name: airwatch_api
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  worker:
    build: ../apps/api
    container_name: airwatch_worker
    env_file:
      - ../.env
    command: celery -A app.worker.celery_app worker -l INFO
    depends_on:
      - postgres
      - redis

  beat:
    build: ../apps/api
    container_name: airwatch_beat
    env_file:
      - ../.env
    command: celery -A app.worker.celery_app beat -l INFO
    depends_on:
      - postgres
      - redis

volumes:
  airwatch_pgdata: